[package]
name = "ring-actions-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
reqwest = { version = "*", features = ["blocking", "rustls-tls"], default-features = false }
